Eliminate static data when unreferenced
ARMmbed/wifi-x-nucleo-idw01m1 pull request #14
Opened 2018-06-12 12:55 UTC by kjbracey-arm

Avoid static ROM + RAM use when driver is not referenced.

Saves about 150 bytes of ROM and 50 bytes of RAM in mbed OS
easy-connect when using a different driver.

Switches mutex locking from built-in BlockExecuter to the
ScopedMutexLock from mbed OS. Using ScopedLock in place of the other
uses of BlockExecuter could be a further potential ROM saving by
statically binding the calls rather than using Callbacks, but might
not be as syntactically neat.

2018-06-19 09:06 UTC, betzw requested changes
Could you pls. remove 
```
Using ScopedLock in place of the other
uses of BlockExecuter could be a further potential ROM saving by
statically binding the calls rather than using Callbacks, but might
not be as syntactically neat.
```
from your commit message. I think that this is misleading.

2018-06-19 09:54 UTC, kjbracey-arm commented
Sure - I just put that comment in to try to justify the `BlockExecuter`/`ScopedLock` mismatch.

Not sure what's misleading though. BlockExecuter is more flexible, but has the complexity of actually creating the `Callback` objects, which I think are complex enough that the compilers will fail to optimise them out.  Or am I underestimating the optimisers?

A `ScopedLock` template instantiation can definitely be simple enough that at least at `-O2`  level it just compiles straight to the relevant function calls with no overhead.

2018-06-19 09:57 UTC, kjbracey-arm commented
Edited, and squashed your cosmetic change in.

2018-06-20 06:43 UTC, betzw approved these changes

2018-06-20 06:43 UTC, merged